name = "PermutationTests"
uuid = "dd25e4c7-56c0-4344-ab7a-80f9379a34f4"
authors = ["Marco Congedo, Livio Finos"]
version = "0.2.2"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Folds = "41a02a25-b8f0-4f67-bc48-60067656b558"
PrecompileSignatures = "91cefc8d-f054-46dc-8f8c-26e11d7c5411"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Combinatorics = "1.0"
Compat = "4.16.0"
Distributions = "0.25.120"
Folds = "0.2"
PrecompileSignatures = "3.0.3"
Statistics = "1.10"
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Statistics", "Test"]
